Update README
RockefellerArchiveCenter/pictor pull request #33
Opened 2021-08-17 18:52 UTC by HaSistrunk

Fixes issue #20 

Can I get some help with adding the routes here?

2021-08-17 19:03 UTC, helrond commented
This should give you what you need: https://github.com/RockefellerArchiveCenter/pictor/blob/development/pictor/urls.py

2021-08-17 21:28 UTC, helrond approved these changes
for the record I'm fine with this being merged even if the build is failing (thanks for nothing Travis)

2021-08-18 13:20 UTC, bonniegee requested changes
One small change--otherwise looks great!

2021-08-18 13:20 UTC, bonniegee commented on README.md
> +contain their ArchivesSpace RefID in the bag-info.txt file. For an example of what pictor expects to receive, see the `fixtures/` directory.
```suggestion
contain their ArchivesSpace URI in the bag-info.txt file. For an example of what pictor expects to receive, see the `fixtures/` directory.
```

2021-08-18 19:34 UTC, p-galligan approved these changes
Looks good to me!

2021-08-18 20:29 UTC, bonniegee approved these changes

2021-08-18 20:39 UTC, merged