Make api version configurable
RockefellerArchiveCenter/pictor pull request #47
Opened 2021-08-31 21:25 UTC by bonniegee

Fixes #39 

Some of the checks are verbose but I was trying to err on readability--open to making changes.

Also want to make sure I'm not missing anything.

2021-09-01 13:02 UTC, helrond requested changes
So there are really two IIIF APIs at play here: the Image API (which controls rotation, zoom, etc) and the Presentation API (which has to do with page sequencing, etc). I think it's a smart idea to track both of these versions, but that needs to be done in separate variables. Most of my comments below flow from the above.

2021-09-01 13:02 UTC, helrond commented on pictor/settings.py
> +IIIF_API_VERSION = CF.IIIF_API_VERSION
Suggest changing this to a dict that has separate keys for `image_api_version` and `presentation_api_version`

2021-09-01 13:02 UTC, helrond commented on pictor/config.py.example
> +IIIF_API_VERSION = 2
See comments on `settings.py`

2021-09-01 13:02 UTC, helrond commented on create_derivatives/routines.py
> +        self.api_version = settings.IIIF_API_VERSION
Should be `image_api_version`

2021-09-01 13:02 UTC, helrond commented on create_derivatives/routines.py
> +            raise Exception("Version {} not supported.".format(self.api_version))
I like this idea but it will need to check both the Presentation and Image API versions.

2021-09-01 13:02 UTC, helrond commented on create_derivatives/routines.py
> +            manifest_json = v3_json
This is a good idea too but should trigger from the Presentation API version, not the Image API version.

2021-09-01 13:21 UTC, p-galligan commented
To add onto Hillel's comments about API versions, here's a [sample image manifest](https://iiif.io/api/cookbook/recipe/0001-mvm-image/). You can see some presentation api declarations there and where you might expect to see them.

2021-09-02 20:48 UTC, helrond requested changes
Very minor tweaks - looks good otherwise!

2021-09-02 20:48 UTC, helrond commented on create_derivatives/routines.py
> +    """Creates a IIIF presentation manifest version 3 from JP2 files.
```suggestion
    """Creates a IIIF presentation manifest from JP2 files.
```

2021-09-02 20:48 UTC, helrond commented on create_derivatives/routines.py
> +            raise Exception("Version {} of presenation API not supported.".format(self.presentation_api_version))
```suggestion
            raise Exception("Version {} of IIIF Presentation API not supported.".format(self.presentation_api_version))
```

2021-09-02 20:48 UTC, helrond commented on create_derivatives/routines.py
> +            raise Exception("Version {} of image API not supported.".format(self.image_api_version))
```suggestion
            raise Exception("Version {} of IIIF Image API not supported.".format(self.image_api_version))
```

2021-09-02 20:48 UTC, helrond commented on create_derivatives/routines.py
>              v3_json = self.upgrader.process_resource(v2_json, top=True)
```suggestion
            manifest_json = self.upgrader.process_resource(v2_json, top=True)
```
And then delete following line.

2021-09-02 20:56 UTC, helrond approved these changes

2021-09-03 13:00 UTC, p-galligan approved these changes

2021-09-03 14:23 UTC, merged