Update canvas page numbers, annotation ids
RockefellerArchiveCenter/pictor pull request #56
Opened 2021-09-14 15:30 UTC by bonniegee

Related to discussion in #50.

2021-09-14 15:43 UTC, helrond reviewed
I don't think we need to iterate up annotations for each canvas - those identifiers will be distinguished by the canvas ids. If we were adding multiple annotations to a canvas we'd want to make sure each had a unique ID but in this case there will always only be one.

2021-09-14 18:56 UTC, helrond commented on create_derivatives/routines.py
>              page_number = get_page_number(jp2_file)
It looks like we're not using the padded page number here anymore so you can just `lstrip` once here and not have to do it twice below.

2021-09-14 18:57 UTC, helrond requested changes
one small thing.

2021-09-14 21:08 UTC, helrond approved these changes

2021-09-15 17:28 UTC, p-galligan approved these changes

2021-09-16 18:28 UTC, merged