Add configs for continuous integration & continuous deployment
RockefellerArchiveCenter/pictor pull request #57
Opened 2021-09-22 21:55 UTC by bonniegee

Updates Travis file, adds deploy scripts and configs.

I added the DJANGO_PORT as a variable available to all branches, but of course I can go with another approach.

2021-09-22 22:30 UTC, helrond requested changes
This mostly looks good but I'd just keep the port mapping to whatever they're running on in the container. It's less complicated/easier to understand what's going on for someone coming to the app without prior knowledge.

2021-09-22 22:30 UTC, helrond commented on docker-compose.yml
> +      - "8000:8012"
```suggestion
      - "8012:8012"
```
Think it makes sense to just keep this all consistent

2021-09-24 16:13 UTC, helrond commented on deploy_scripts/substitute_env.sh
> +for TEMPLATE in pictor/config.py.deploy \
We have the application name as an environment variable in Travis, right? So we could do 
```suggestion
for TEMPLATE in &{APPLICATION_NAME}/config.py.deploy \
```

2021-09-24 16:13 UTC, helrond commented on deploy_scripts/stop_cron.sh.deploy
> +  sudo pkill -f pictor.*runcrons
Same here, we could use the ${APPLICATION_NAME} variable.

2021-09-24 16:17 UTC, helrond requested changes
There's a couple of things I think that can be done in the deploy scripts to further abstract. Ultimately when we get around to the CD portion of our work I think we'll want to have these scripts in one place and then have apps pull them in in the deploy process, so the more we can remove hardcoded values the better.

Also, I've heard from external partners that having some comments in the config file which indicate what those configs are as well as any gotchas about values is super helpful. See Pisces for an example: https://github.com/RockefellerArchiveCenter/pisces/blob/base/pisces/config.py.example

2021-09-24 17:48 UTC, helrond approved these changes
Heck yeah

2021-09-24 18:05 UTC, p-galligan approved these changes
Looks good!

I'm assuming the secret_key in the config example is something we don't mind being public?

2021-09-24 18:16 UTC, bonniegee commented
> I'm assuming the secret_key in the config example is something we don't mind being public?

Yep, this is not actually used in a deploy anywhere.

2021-09-27 18:09 UTC, merged